server:
  port: 8080
  #servlet:
    #context-path: /api

spring:
  application:
    name: cv-agent
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/cvagent
      database: cvagent

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m
  # Spring Security配置
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    com.cvagent: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# OpenAI配置
openai:
  api-key: ${DASHSCOPE_API_KEY}
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: qwen-plus

# 文件上传配置
file:
  upload:
    max-size: 10MB
    allowed-types: application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document
  storage:
    path: ${FILE_STORAGE_PATH:./uploads}

# JWT配置
app:
  jwt:
    secret: mySecretKeyForCvAgentApplicationShouldBeVeryLongAndSecure
    expiration-in-ms: 86400000 # 24小时



